"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: vicon_bridge2
  IDL file: Pose6D.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import ViconBridge


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Pose6D(idl.IdlStruct, typename="vicon_bridge2.Pose6D"):
    stamp_nano_secs: types.uint64
    q: types.array[types.float64, 7]
    t: types.array[types.float64, 3]


