/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/vicon-ws/src/vicon_bridge2/vicon_bridge2/Pose6D.idl
  Source: Pose6D.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "Pose6D.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace vicon_bridge2
{
std::ostream& operator<<(std::ostream& os, Pose6D const& rhs)
{
  (void) rhs;
  os << "[";
  os << "stamp_nano_secs: " << rhs.stamp_nano_secs();
  os << ", q: " << rhs.q();
  os << ", t: " << rhs.t();
  os << "]";
  return os;
}

} //namespace vicon_bridge2

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::vicon_bridge2::Pose6D>() {
  static std::mutex mtx;
  static propvec props;
  static std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed))
    return props;
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed))
    return props;
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<uint64_t>(), extensibility::ext_final, false));  //::stamp_nano_secs
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::q
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<double>(), extensibility::ext_final, false));  //::t

  entity_properties_t::finish(props, keylist);
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

